MVCPedidos/Controllers/OrdenModelsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MVCPedidos.Data;
using MVCPedidos.Models;

namespace MVCPedidos.Controllers
{
    public class OrdenModelsController : Controller
    {
        private readonly PedidosDBContext _context;

        public OrdenModelsController(PedidosDBContext context)
        {
            _context = context;
        }

        // GET: OrdenModels
        public async Task<IActionResult> Index()
        {
            var pedidosDBContext = _context.Orden.Include(o => o.Usuario);
            return View(await pedidosDBContext.ToListAsync());
        }

        // GET: OrdenModels/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ordenModel = await _context.Orden
                .Include(o => o.Usuario)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (ordenModel == null)
            {
                return NotFound();
            }

            return View(ordenModel);
        }

        // GET: OrdenModels/Create
        public IActionResult Create()
        {
            ViewData["IdUsuario"] = new SelectList(_context.Usuario, "Id", "Email");
            return View();
        }

        // POST: OrdenModels/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,IdUsuario,Fecha,Estado,Total")] OrdenModel ordenModel)
        {
            //if (ModelState.IsValid)
            //{
                _context.Add(ordenModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            //}
            ViewData["IdUsuario"] = new SelectList(_context.Usuario, "Id", "Email", ordenModel.IdUsuario);
            return View(ordenModel);
        }

        // GET: OrdenModels/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ordenModel = await _context.Orden.FindAsync(id);
            if (ordenModel == null)
            {
                return NotFound();
            }
            ViewData["IdUsuario"] = new SelectList(_context.Usuario, "Id", "Email", ordenModel.IdUsuario);
            return View(ordenModel);
        }

        // POST: OrdenModels/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,IdUsuario,Fecha,Estado,Total")] OrdenModel ordenModel)
        {
            if (id != ordenModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(ordenModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OrdenModelExists(ordenModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdUsuario"] = new SelectList(_context.Usuario, "Id", "Email", ordenModel.IdUsuario);
            return View(ordenModel);
        }

        // GET: OrdenModels/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ordenModel = await _context.Orden
                .Include(o => o.Usuario)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (ordenModel == null)
            {
                return NotFound();
            }

            return View(ordenModel);
        }

        // POST: OrdenModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var ordenModel = await _context.Orden.FindAsync(id);
            if (ordenModel != null)
            {
                _context.Orden.Remove(ordenModel);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OrdenModelExists(int id)
        {
            return _context.Orden.Any(e => e.Id == id);
        }
    }
}

MVCPedidos/Controllers/ProductoModelsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MVCPedidos.Data;
using MVCPedidos.Models;

namespace MVCPedidos.Controllers
{
    public class ProductoModelsController : Controller
    {
        private readonly PedidosDBContext _context;

        public ProductoModelsController(PedidosDBContext context)
        {
            _context = context;
        }

        // GET: ProductoModels
        
        public async Task<IActionResult> Index()
        {
            return View(await _context.Producto.ToListAsync());
        }

        // GET: ProductoModels/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var productoModel = await _context.Producto
                .FirstOrDefaultAsync(m => m.Id == id);
            if (productoModel == null)
            {
                return NotFound();
            }

            return View(productoModel);
        }

        // GET: ProductoModels/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: ProductoModels/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nombre,Descripcion,Precio,Stock")] ProductoModel productoModel)
        {
            //if (ModelState.IsValid)
            //{
                _context.Add(productoModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            //}
            return View(productoModel);
        }

        // GET: ProductoModels/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var productoModel = await _context.Producto.FindAsync(id);
            if (productoModel == null)
            {
                return NotFound();
            }
            return View(productoModel);
        }

        // POST: ProductoModels/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nombre,Descripcion,Precio,Stock")] ProductoModel productoModel)
        {
            if (id != productoModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(productoModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductoModelExists(productoModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(productoModel);
        }

        // GET: ProductoModels/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var productoModel = await _context.Producto
                .FirstOrDefaultAsync(m => m.Id == id);
            if (productoModel == null)
            {
                return NotFound();
            }

            return View(productoModel);
        }

        // POST: ProductoModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var productoModel = await _context.Producto.FindAsync(id);
            if (productoModel != null)
            {
                _context.Producto.Remove(productoModel);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductoModelExists(int id)
        {
            return _context.Producto.Any(e => e.Id == id);
        }
    }
}

MVCPedidos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVCPedidos</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVCPedidos.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom box-shadow">
            <div class="container-fluid">
                <a class="navbar-brand text-white" asp-controller="Home" asp-action="Index">ProyectoMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-controller="Home" asp-action="Index">Inicio</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            @if (User.IsInRole("Admin"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-white" asp-controller="Admin" asp-action="Index">Panel Admin</a>
                                </li>
                            }
                            @if (User.IsInRole("Admin") || User.IsInRole("Usuario"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-white" asp-controller="Tienda" asp-action="Index">Tienda</a>
                                </li>
                            }
                        }
                    </ul>
                    <ul class="navbar-nav">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <span class="navbar-text me-3 text-white">
                                    Hola, @User.FindFirst("nombreCompleto")?.Value
                                    <span class="badge bg-primary">@User.FindFirst(System.Security.Claims.ClaimTypes.Role)?.Value</span>
                                </span>
                            </li>
                            <li class="nav-item">
                                <form method="post" asp-controller="Account" asp-action="Logout" class="d-inline">
                                    <button type="submit" class="btn btn-link nav-link">Cerrar sesión</button>
                                </form>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-controller="Account" asp-action="Login">Iniciar sesión</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-controller="Account" asp-action="Register">Registrarse</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="d-flex">
    <div class="bg-dark text-white p-3" style="width: 220px; height: 100vh;">
        <h4 class="text-center mb-4">Menu</h4>
        <ul class="nav flex-column">
            <li class="nav-item">
                <a class="nav-link text-white" asp-controller="Home" asp-action="Index">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-white" asp-controller="ProductoModels" asp-action="Index">Producto</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-white" asp-controller="OrdenModels" asp-action="Index">Pedidos</a>
            </li>
        </ul>
    </div>
    <div class="flex-grow-1 p-4">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - MVCPedidos - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    </div>
</body>
</html>